-- Schema de tarefas/projetos/tempo para Supabase (Postgres)
-- Ordem: clientes -> colaboradores_cliente -> projects -> tasks -> elapsed_times -> users -> reponsonsibles_tasks_users

-- Enum para tipo de horas contratadas
CREATE TYPE IF NOT EXISTS public.tipo_horas_enum AS ENUM ('HG', 'HP');

CREATE TABLE IF NOT EXISTS public.clientes (
  cliente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  tipo_horas public.tipo_horas_enum NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  horas_hg_contratadas DOUBLE PRECISION,
  horas_contratadas NUMERIC NOT NULL DEFAULT 0,
  horas_consumidas NUMERIC NOT NULL DEFAULT 0,
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.colaboradores_cliente (
  colaborador_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES public.clientes(cliente_id),
  nome TEXT NOT NULL,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  auth_user_id UUID UNIQUE REFERENCES auth.users(id)
);

CREATE INDEX IF NOT EXISTS idx_colaboradores_cliente_cliente_id ON public.colaboradores_cliente(cliente_id);
CREATE INDEX IF NOT EXISTS idx_colaboradores_cliente_auth_user_id ON public.colaboradores_cliente(auth_user_id);

CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active BOOLEAN DEFAULT FALSE,
  name TEXT NOT NULL,
  description TEXT,
  keywords TEXT,
  closed BOOLEAN DEFAULT FALSE,
  visible BOOLEAN DEFAULT FALSE,
  opened BOOLEAN DEFAULT FALSE,
  date_create TIMESTAMPTZ DEFAULT now(),
  date_update TIMESTAMPTZ DEFAULT now(),
  date_activity TIMESTAMPTZ,
  number_of_members BIGINT DEFAULT 1,
  project BOOLEAN DEFAULT FALSE,
  project_date_start TIMESTAMPTZ,
  project_date_finish TIMESTAMPTZ,
  type TEXT,
  horas_contratadas NUMERIC DEFAULT 10,
  cliente_id BIGINT REFERENCES public.clientes(cliente_id)
);

CREATE INDEX IF NOT EXISTS idx_projects_cliente_id ON public.projects(cliente_id);

CREATE TABLE IF NOT EXISTS public.tasks (
  task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status INTEGER,
  deadline TIMESTAMPTZ,
  closed_date TIMESTAMPTZ,
  group_id BIGINT,
  group_name TEXT,
  responsible_id BIGINT,
  responsible_name TEXT,
  inserted_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  project_id BIGINT REFERENCES public.projects(id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON public.tasks(project_id);

CREATE TABLE IF NOT EXISTS public.elapsed_times (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES public.tasks(task_id),
  user_id BIGINT,
  comment_text TEXT,
  date_start TIMESTAMPTZ,
  created_date TIMESTAMPTZ,
  date_stop TIMESTAMPTZ,
  minutes INTEGER,
  seconds INTEGER,
  source TEXT,
  inserted_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_elapsed_times_task_id ON public.elapsed_times(task_id);

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  xml_id TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  last_login TIMESTAMPTZ,
  date_register TIMESTAMPTZ,
  time_zone TEXT,
  is_online CHARACTER,
  timestamp_x JSONB,
  last_activity_date JSONB,
  personal_gender CHARACTER,
  personal_www TEXT,
  personal_birthday DATE,
  personal_photo TEXT,
  personal_mobile TEXT,
  personal_city TEXT,
  work_phone TEXT,
  work_position TEXT,
  uf_employment_date DATE,
  uf_department TEXT[],
  user_type TEXT,
  auth_user_id UUID UNIQUE REFERENCES auth.users(id),
  user_profile JSONB
);

CREATE INDEX IF NOT EXISTS idx_users_auth_user_id ON public.users(auth_user_id);

-- Mantido o nome original da tabela (com typo) para compatibilidade
CREATE TABLE IF NOT EXISTS public.reponsonsibles_tasks_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  xml_id TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  name TEXT NOT NULL,
  last_name TEXT,
  second_name TEXT,
  email TEXT UNIQUE,
  last_login TIMESTAMPTZ,
  date_register TIMESTAMPTZ,
  time_zone TEXT,
  is_online CHARACTER,
  timestamp_x JSONB,
  last_activity_date JSONB,
  personal_gender CHARACTER,
  personal_www TEXT,
  personal_birthday DATE,
  personal_photo TEXT,
  personal_mobile TEXT,
  personal_city TEXT,
  work_phone TEXT,
  work_position TEXT,
  uf_employment_date DATE,
  uf_department TEXT[],
  user_type TEXT,
  auth_user_id UUID UNIQUE REFERENCES auth.users(id),
  user_profile JSONB
);

CREATE INDEX IF NOT EXISTS idx_reponsonsibles_auth_user_id ON public.reponsonsibles_tasks_users(auth_user_id);
